// LAYER 227
---functions---
help.getConfig#c4f9186b = Config;

---types---
userEmpty#d3bc4b7a id:long = User;
userStatusEmpty#9d05049 = UserStatus;
userStatusOnline#edb93949 expires:int = UserStatus;
messages.messages#1d73e7ea messages:Vector<Message> topics:Vector<ForumTopic> chats:Vector<Chat> users:Vector<User> = messages.Messages;
msgs_state_info#04deb57d req_msg_id:long info:string = MsgsStateInfo;
